security:
#    encoders:
#        App\Entity\User:
#            algorithm: argon2i

    encoders:
          App\Entity\User:
              algorithm: bcrypt
              cost: 12

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        form_database:
            entity:
                class: App/Entity/User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail

        oauth:
            id: knpu.oauth2.user_provider
        # used to reload user from session & other features (e.g. switch_user)
#        in_memory:
#            memory:
#                users:
#                    demo:
#                        password: demo
#                        roles : ROLE_ADMIN
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: app_user_provider
            form_login:
                login_path: security_login
                check_path: security_login

            logout:
                path: security_logout
                target: property.index

            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator
#                    -  App\Security\Authenticator\FacebookAuthenticator
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }







